### ISSUE TITLE
error

### ISSUE THREAD

**Issue by RicardPort** [Peanut1120/sellix-bot#1]
hello 

do you know why i get errors ? i dont understand little bit step 3 

`
Step 3
Go to the sellix dashboard, open up the developers module and click on webhook, add one. Firstly put the domain as https://yourdomain.com/api/getorder then set the event as order:paid`

i did somthing like this >>

![image](https://user-images.githubusercontent.com/79153428/123529131-c5db2a00-d6ed-11eb-9f93-ec62c3576076.png)

![image](https://user-images.githubusercontent.com/79153428/123528978-83fdb400-d6ec-11eb-93ce-2c8e3ea0e53c.png)

![image](https://user-images.githubusercontent.com/79153428/123528992-9aa40b00-d6ec-11eb-849a-3d5fd87b9b3f.png)

**Comment by patrickmcm** [comment]
Hi, firstly the syntax for the get order command is
!getorder orderidhere 

Make sure you have put your sellix api key in config.json, search it up if you don't know how to get it. 


Secondly discord ID is for IDS not tags, - watch this to see how to get your ID: https://youtu.be/VTgVsQ0gwKM

**Comment by patrickmcm** [comment]
Secondly this requires a server to run on like heroku, this isn't for discord webhooks.
