### ISSUE TITLE
TypeError: Cannot read property 'Discord ID' of undefined

### ISSUE THREAD

**Issue by LW-S111** [Peanut1120/sellix-bot#2]
Hi,
I'm confronted with this problem, and I can't find any solution.
I tried with an api tester, and buying an item on my sellix shop.
But in both cases it doesn't find the "Discord ID". 
Would you have an idea to solve this problem?
Thanks a lot.

The error:
![Screenshot_8](https://user-images.githubusercontent.com/89352649/130365468-64f785a3-2722-498a-8f0c-622f78b0a70e.png)

Sellix Custom Fields:
![Screenshot_7](https://user-images.githubusercontent.com/89352649/130365469-c3e8fe66-4ae8-405e-8c2a-d287ae4d0563.png)

And when I tried with an api tester:
![Screenshot_6](https://user-images.githubusercontent.com/89352649/130365470-a798823a-3a07-4c6e-86d3-4cc57bb7eeaa.png)

**Comment by LW-S111** [comment]
ok I fix:
![image](https://user-images.githubusercontent.com/89352649/130365997-064a22fa-aa6f-4d7c-878b-1e743b8bdaab.png)

but new problem:
```
DiscordAPIError: Unknown User
    at RequestHandler.execute (/home/runner/botdiscord/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/botdiscord/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async UserManager.fetch (/home/runner/botdiscord/node_modules/discord.js/src/managers/UserManager.js:67:18)
    at async /home/runner/botdiscord/routes/apiRouter.js:13:18 {
  method: 'get',
  path: '/users/452186417334976500',
  code: 10013,
  httpStatus: 404
}
```

**Comment by Peanut1120** [comment]
Hi, Make sure that in the custom field on the sellix dashboard that it is registered as a string otherwise node will try and round up the number causing your error.

**Comment by LW-S111** [comment]
> Hi, Make sure that in the custom field on the sellix dashboard that it is registered as a string otherwise node will try and round up the number causing your error.

Thanks a lot, it works, I found the error, it was pretty stupid, thanks a lot for your code!
(Yes, I had to put the user id as a string and not as a number.)
